#include "vibe_input_router.h"

vibe_app_command_t vibe_input_router_command(vibe_input_signal_t signal)
{
    switch (signal) {
    case VIBE_INPUT_SIGNAL_FRONT_SINGLE:
        return VIBE_STICK_EVENT_RECORDING_TOGGLE;
    case VIBE_INPUT_SIGNAL_FRONT_DOUBLE:
        return VIBE_STICK_EVENT_DOUBLE_CLICK;
    case VIBE_INPUT_SIGNAL_FRONT_LONG_START:
        return VIBE_STICK_EVENT_LONG_START;
    case VIBE_INPUT_SIGNAL_FRONT_LONG_STOP:
        return VIBE_STICK_EVENT_LONG_STOP;
    case VIBE_INPUT_SIGNAL_SIDE_MODE:
        return VIBE_STICK_EVENT_RECORDING_MODE_TOGGLE;
    case VIBE_INPUT_SIGNAL_SIDE_CALIBRATE:
        return VIBE_STICK_EVENT_MOTION_CALIBRATE;
    case VIBE_INPUT_SIGNAL_SIDE_SCAN:
        return VIBE_STICK_EVENT_BRIDGE_SCAN_FULL;
    case VIBE_INPUT_SIGNAL_MOTION_LIFTED:
        return VIBE_STICK_EVENT_MOTION_START;
    case VIBE_INPUT_SIGNAL_MOTION_FLAT:
        return VIBE_STICK_EVENT_MOTION_STOP;
    case VIBE_INPUT_SIGNAL_CARD_OPT_TAP:
        return VIBE_STICK_EVENT_CARD_OPT_TAP;
    case VIBE_INPUT_SIGNAL_CARD_OPT_DOUBLE:
        return VIBE_STICK_EVENT_CARD_OPT_DOUBLE;
    case VIBE_INPUT_SIGNAL_CARD_OPT_HOLD_START:
        return VIBE_STICK_EVENT_CARD_OPT_HOLD_START;
    case VIBE_INPUT_SIGNAL_CARD_OPT_HOLD_STOP:
        return VIBE_STICK_EVENT_CARD_OPT_HOLD_STOP;
    default:
        return VIBE_APP_COMMAND_NONE;
    }
}
