#pragma once

typedef enum {
    VIBE_APP_COMMAND_NONE = 0,
    VIBE_STICK_EVENT_POLL_STATE,
    VIBE_STICK_EVENT_RECORDING_TOGGLE,
    VIBE_STICK_EVENT_DOUBLE_CLICK,
    VIBE_STICK_EVENT_LONG_START,
    VIBE_STICK_EVENT_LONG_STOP,
    VIBE_STICK_EVENT_PROVIDER_NEXT,
    VIBE_STICK_EVENT_RECORDING_MODE_TOGGLE,
    VIBE_STICK_EVENT_RECORDING_INTENT_TOGGLE,
    VIBE_STICK_EVENT_MOTION_CALIBRATE,
    VIBE_STICK_EVENT_MOTION_START,
    VIBE_STICK_EVENT_MOTION_STOP,
    VIBE_STICK_EVENT_TTS_PROBE,
    VIBE_STICK_EVENT_OTA_CHECK,
    VIBE_STICK_EVENT_BRIDGE_SCAN_FULL,
    VIBE_STICK_EVENT_SETTINGS_ENTER,
    VIBE_STICK_EVENT_SETTINGS_PAGE_NEXT,
    VIBE_STICK_EVENT_SETTINGS_VALUE_NEXT,
    VIBE_STICK_EVENT_SETTINGS_CONFIRM,
    VIBE_STICK_EVENT_CARD_OPT_TAP,
    VIBE_STICK_EVENT_CARD_OPT_DOUBLE,
    VIBE_STICK_EVENT_CARD_OPT_HOLD_START,
    VIBE_STICK_EVENT_CARD_OPT_HOLD_STOP,
    VIBE_STICK_EVENT_CARD_OPT_COMPLETE,
} vibe_app_command_t;

typedef struct {
    vibe_app_command_t type;
} vibe_app_event_t;
