#pragma once

#include "vibe_app_command.h"

typedef enum {
    VIBE_INPUT_SIGNAL_FRONT_SINGLE,
    VIBE_INPUT_SIGNAL_FRONT_DOUBLE,
    VIBE_INPUT_SIGNAL_FRONT_LONG_START,
    VIBE_INPUT_SIGNAL_FRONT_LONG_STOP,
    VIBE_INPUT_SIGNAL_SIDE_MODE,
    VIBE_INPUT_SIGNAL_SIDE_CALIBRATE,
    VIBE_INPUT_SIGNAL_SIDE_SCAN,
    VIBE_INPUT_SIGNAL_MOTION_LIFTED,
    VIBE_INPUT_SIGNAL_MOTION_FLAT,
    VIBE_INPUT_SIGNAL_CARD_OPT_TAP,
    VIBE_INPUT_SIGNAL_CARD_OPT_DOUBLE,
    VIBE_INPUT_SIGNAL_CARD_OPT_HOLD_START,
    VIBE_INPUT_SIGNAL_CARD_OPT_HOLD_STOP,
} vibe_input_signal_t;

vibe_app_command_t vibe_input_router_command(vibe_input_signal_t signal);
