#pragma once

#include "driver/gpio.h"
#include "driver/i2c_types.h"
#include "driver/i2s_types.h"
#include "driver/spi_master.h"

#if defined(VIBE_BOARD_STICKC_PLUS)

// M5StickC Plus 1.1 hardware profile.
#define VIBE_BOARD_NAME "stickc_plus"
#define VIBE_BOARD_EVENT_SOURCE "stickc_plus"
#define VIBE_BOARD_AUDIO_SOURCE "stickc_plus_pcm"

#define VIBE_BOARD_MODEL_NAME "M5StickC Plus 1.1"
#define VIBE_BOARD_BATTERY_CAPACITY_MAH 120
#define VIBE_BOARD_HAS_ES8311 0
#define VIBE_BOARD_HAS_PDM_MIC 1
#define VIBE_BOARD_HAS_GPIO_TONE_SPEAKER 1
#define VIBE_BOARD_HAS_GPIO_BACKLIGHT 0
#define VIBE_BOARD_HAS_MPU6886 1
#define VIBE_BOARD_HAS_BMI270 0
#define VIBE_BOARD_HAS_LIFT_TO_TALK 1
#define VIBE_BOARD_HAS_IMU_DEEP_SLEEP_WAKE 1
#define VIBE_BOARD_HAS_CYBER_INTENTS 0

#define VIBE_BOARD_LCD_HOST SPI2_HOST
#define VIBE_BOARD_LCD_H_RES 135
#define VIBE_BOARD_LCD_V_RES 240
#define VIBE_BOARD_LCD_X_GAP 52
#define VIBE_BOARD_LCD_Y_GAP 40
#define VIBE_BOARD_LCD_PIXEL_CLOCK_HZ (20 * 1000 * 1000)
#define VIBE_BOARD_LCD_SPI_SIO_MODE 0
#define VIBE_BOARD_LCD_BACKLIGHT_GPIO GPIO_NUM_NC
#define VIBE_BOARD_LCD_BACKLIGHT_DEFAULT 150
#define VIBE_BOARD_LCD_BACKLIGHT_IDLE 45
#define VIBE_BOARD_LCD_BACKLIGHT_OFF 0
#define VIBE_BOARD_AXP192_BRIGHTNESS_MIN 7
#define VIBE_BOARD_AXP192_BRIGHTNESS_MAX 12
#define VIBE_BOARD_AXP192_CHARGE_CURRENT_MA 100
#define VIBE_BOARD_AXP192_CHARGE_CTRL1 0xc0

#define VIBE_BOARD_PIN_BUTTON_FRONT GPIO_NUM_37
#define VIBE_BOARD_PIN_BUTTON_SIDE GPIO_NUM_39
#define VIBE_BOARD_PIN_IMU_INT GPIO_NUM_35
#define VIBE_BOARD_PIN_LCD_MOSI GPIO_NUM_15
#define VIBE_BOARD_PIN_LCD_SCK GPIO_NUM_13
#define VIBE_BOARD_PIN_LCD_DC GPIO_NUM_23
#define VIBE_BOARD_PIN_LCD_CS GPIO_NUM_5
#define VIBE_BOARD_PIN_LCD_RST GPIO_NUM_18
#define VIBE_BOARD_PIN_I2C_SDA GPIO_NUM_21
#define VIBE_BOARD_PIN_I2C_SCL GPIO_NUM_22
#define VIBE_BOARD_PIN_PDM_CLK GPIO_NUM_0
#define VIBE_BOARD_PIN_PDM_DATA GPIO_NUM_34
#define VIBE_BOARD_PIN_SPEAKER GPIO_NUM_2

#define VIBE_BOARD_I2C_PORT I2C_NUM_0
#define VIBE_BOARD_I2S_PORT I2S_NUM_0

#else

#define VIBE_BOARD_STICKS3 1
#define VIBE_BOARD_NAME "sticks3"
#define VIBE_BOARD_EVENT_SOURCE "sticks3"
#define VIBE_BOARD_AUDIO_SOURCE "sticks3_pcm"

#define VIBE_BOARD_HAS_ES8311 1
#define VIBE_BOARD_HAS_PDM_MIC 0
#define VIBE_BOARD_HAS_GPIO_TONE_SPEAKER 0
#define VIBE_BOARD_HAS_GPIO_BACKLIGHT 1
#define VIBE_BOARD_HAS_MPU6886 0
#define VIBE_BOARD_HAS_BMI270 1
#define VIBE_BOARD_HAS_LIFT_TO_TALK 1
#define VIBE_BOARD_HAS_IMU_DEEP_SLEEP_WAKE 0
#define VIBE_BOARD_HAS_CYBER_INTENTS 1

#define VIBE_BOARD_LCD_HOST SPI2_HOST
#define VIBE_BOARD_LCD_H_RES 135
#define VIBE_BOARD_LCD_V_RES 240
#define VIBE_BOARD_LCD_X_GAP 52
#define VIBE_BOARD_LCD_Y_GAP 40
#define VIBE_BOARD_LCD_PIXEL_CLOCK_HZ (20 * 1000 * 1000)
#define VIBE_BOARD_LCD_SPI_SIO_MODE 1
#define VIBE_BOARD_LCD_BACKLIGHT_GPIO GPIO_NUM_38
#define VIBE_BOARD_LCD_BACKLIGHT_DEFAULT 150
#define VIBE_BOARD_LCD_BACKLIGHT_IDLE 45
#define VIBE_BOARD_LCD_BACKLIGHT_OFF 0

#define VIBE_BOARD_PIN_BUTTON_FRONT GPIO_NUM_11
#define VIBE_BOARD_PIN_BUTTON_SIDE GPIO_NUM_12
#define VIBE_BOARD_PIN_IMU_INT GPIO_NUM_NC
#define VIBE_BOARD_PIN_LCD_MOSI GPIO_NUM_39
#define VIBE_BOARD_PIN_LCD_SCK GPIO_NUM_40
#define VIBE_BOARD_PIN_LCD_DC GPIO_NUM_45
#define VIBE_BOARD_PIN_LCD_CS GPIO_NUM_41
#define VIBE_BOARD_PIN_LCD_RST GPIO_NUM_21
#define VIBE_BOARD_PIN_I2C_SDA GPIO_NUM_47
#define VIBE_BOARD_PIN_I2C_SCL GPIO_NUM_48
#define VIBE_BOARD_PIN_ES8311_MCLK GPIO_NUM_18
#define VIBE_BOARD_PIN_ES8311_BCLK GPIO_NUM_17
#define VIBE_BOARD_PIN_ES8311_LRCK GPIO_NUM_15
#define VIBE_BOARD_PIN_ES8311_DIN GPIO_NUM_14
#define VIBE_BOARD_PIN_ES8311_DOUT GPIO_NUM_16

#define VIBE_BOARD_I2C_PORT I2C_NUM_1
#define VIBE_BOARD_I2S_PORT I2S_NUM_1

#endif
