#pragma once

#define FIRMWARE_NAME "vibestick"
#define VIBE_STICK_FIRMWARE_VERSION_CARDPUTER_ADV "0.1.74"
#define FIRMWARE_VERSION VIBE_STICK_FIRMWARE_VERSION_CARDPUTER_ADV
#define TRANSPORT "HTTP"
#define VIBE_STICK_RECORDING_START_PATH "/recording/start"
#define VIBE_STICK_RECORDING_AUDIO_PATH "/recording/audio"
#define VIBE_STICK_RECORDING_STOP_PATH "/recording/stop"
#define VIBE_STICK_DEVICE_KEYBOARD_REPORT_PATH "/device/keyboard/report"

#define VIBE_CARDPUTER_BOARD_NAME "cardputer_adv"
#define VIBE_CARDPUTER_EVENT_SOURCE "cardputer_adv"
#define VIBE_CARDPUTER_AUDIO_SOURCE "cardputer_adv_pcm"
#define VIBE_CARDPUTER_WIFI_MAX_TX_POWER 52

#ifndef VIBE_STICK_BRIDGE_TOKEN
#define VIBE_STICK_BRIDGE_TOKEN ""
#endif
#ifndef VIBE_STICK_CARDPUTER_MINIMAL_BRIDGE_HOST
#define VIBE_STICK_CARDPUTER_MINIMAL_BRIDGE_HOST "192.168.100.142"
#endif
#ifndef VIBE_STICK_CARDPUTER_MINIMAL_BRIDGE_PORT
#define VIBE_STICK_CARDPUTER_MINIMAL_BRIDGE_PORT 8765
#endif
